# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skit < Formula
  desc "Small, reproducible Skill manager for agent ecosystems"
  homepage "https://github.com/vlln/skit"
  version "0.4.1"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vlln/skit/releases/download/v0.4.1/skit_Darwin_x86_64.tar.gz"
      sha256 "e1841f127b315c8dcfc16013825f458bc8a93707b2efc19258602195498261a1"

      define_method(:install) do
        bin.install "skit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vlln/skit/releases/download/v0.4.1/skit_Darwin_arm64.tar.gz"
      sha256 "63323d0817c1579aa85bd2490250650351bfa0cbae7d3f6897b8374c02209869"

      define_method(:install) do
        bin.install "skit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vlln/skit/releases/download/v0.4.1/skit_Linux_x86_64.tar.gz"
      sha256 "4dad8ae709a084fa6382c1d755d115325cbe0e40d4f9684598d107007522ca0a"
      define_method(:install) do
        bin.install "skit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vlln/skit/releases/download/v0.4.1/skit_Linux_arm64.tar.gz"
      sha256 "546105b044de1fa7f96d0679c7b8e4e88b3969623c9fd23f90870538194ddb18"
      define_method(:install) do
        bin.install "skit"
      end
    end
  end

  test do
    system "#{bin}/skit", "version"
  end
end
