# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skit < Formula
  desc "Small, reproducible Skill manager for agent ecosystems"
  homepage "https://github.com/vlln/skit"
  version "0.5.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vlln/skit/releases/download/v0.5.0/skit_Darwin_x86_64.tar.gz"
      sha256 "a7d570e46fcec047359fd808a53f8a6a4386a758f000d9be39ee2bafb73c7413"

      define_method(:install) do
        bin.install "skit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vlln/skit/releases/download/v0.5.0/skit_Darwin_arm64.tar.gz"
      sha256 "f9fe1531c9c7d201cce119239ecbc18f715cb10359d09ba51c33fc0760ce7d55"

      define_method(:install) do
        bin.install "skit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vlln/skit/releases/download/v0.5.0/skit_Linux_x86_64.tar.gz"
      sha256 "a9197d9604ddd6b101712484abfbc46db1dc3f0fc4eac0cb9835d6d60606b5b5"
      define_method(:install) do
        bin.install "skit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vlln/skit/releases/download/v0.5.0/skit_Linux_arm64.tar.gz"
      sha256 "10c398a0c942bed8192e277ef1f5f47387a1c600c6c7559c74695f5ae8127d82"
      define_method(:install) do
        bin.install "skit"
      end
    end
  end

  test do
    system "#{bin}/skit", "version"
  end
end
